// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evfqmqbzgxigvvjfbftv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZnFtcWJ6Z3hpZ3Z2amZiZnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjYxODUsImV4cCI6MjA2NzY0MjE4NX0.LHpHKOitxca8hJrqGMUz0hyxanI86sW77NFHeIE_kRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});